version: '3'

services: 


  server:
    build: ./server
    ports: 
      - 8000:8000    
    volumes: 
      - ./server/:/server
    command: uvicorn app.main:app --reload --host localhost --port 8000


  client:  
    build: ./client
    ports: 
      - 4200:4200
    links: 
      - server      
    command: npm run start